#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

export SINGULARITYENV_OMP_NUM_THREADS=7

set -e
set -x

mkdir -p output
cp $(jq -r .bvecs config.json) output/dwi.bvecs
cp $(jq -r .bvals config.json) output/dwi.bvals
chmod -R +w output

time singularity exec -e docker://brainlife/dipy:1.1.1 dipy_gibbs_ringing \
    --force \
    --out_dir output \
    --slice_axis $(jq -r .slice_axis config.json) \
    --n_points $(jq -r .n_points config.json) \
    --out_unring dwi.nii.gz \
    $(jq -r .dwi config.json)

echo "done"
