#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

set -e
set -x

cmd=`jq -r .command config.json`
case "$cmd" in

    dipy_gibbs_ringing)
        cat > script.sh <<EOF
#!/bin/bash
$cmd --force \
    --out_dir $(pwd) \
    --slice_axis $(jq -r .slice_axis config.json) \
    --n_points $(jq -r .n_points config.json) \
    --out_unring dwi.nii.gz \
    $(jq -r .dwi config.json)
EOF
        ;;
    *)
        echo "invalid command: $cmd"
        exit 1
esac

chmod +x script.sh
SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:1.1.1 ./script.sh

echo "done"